test husky

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,18 +1,16 @@
-# # Run Prettier
-# echo "Running Prettier..."
-# pnpm run format || {
-#     echo "Prettier failed. Please fix the formatting issues and try committing again."
-#     exit 1
-# }
-
-# # Run TypeScript check
-# echo "Running TypeScript check..."
-# pnpm run check-ts || {
-#     echo "TypeScript check failed. Please fix the type errors and try committing again."
-#     exit 1
-# }
-
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-pnpm run format
+# Run Prettier
+echo "Running Prettier..."
+pnpm run format || {
+    echo "Prettier failed. Please fix the formatting issues and try committing again."
+    exit 1
+}
+
+# Run TypeScript check
+echo "Running TypeScript check..."
+pnpm run check-ts || {
+    echo "TypeScript check failed. Please fix the type errors and try committing again."
+    exit 1
+}
