test husky

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -5,9 +5,14 @@
 #     exit 1
 # }
 
-# Run TypeScript check
-echo "Running Lint check..."
-pnpm run lint || {
-    echo "Lint check failed. Please fix the type errors and try committing again."
-    exit 1
-}
+# # Run TypeScript check
+# echo "Running TypeScript check..."
+# pnpm run check-ts || {
+#     echo "TypeScript check failed. Please fix the type errors and try committing again."
+#     exit 1
+# }
+
+#!/usr/bin/env sh
+. "$(dirname -- "$0")/_/husky.sh"
+
+pnpm run format
